name: Build paper website and deploy to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'paper/**'
    - '!paper/README.md'
    - '!paper/main.pdf'
    - '.github/workflows/build-website.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jayanthkoushik/paje@v6
      with:
        setupscript: |
          cp paper/main.md /www/index.md
          cp paper/references.bib /www/_includes/
          cp -r paper/sections /www/_includes/
          cp -r paper/tables /www/_includes/
          cp -r paper/tables_stats/_www /www/_includes/tables_stats
          cp -r paper/utils /www/_includes/
          cp -r paper/figures/_www /www/figures
        targetbranch: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
